@dot_net_core_rest_api_HostAddress = http://localhost:5101

### Get all categories
GET {{dot_net_core_rest_api_HostAddress}}/api/categories
Accept: application/json

### Get category by id
GET {{dot_net_core_rest_api_HostAddress}}/api/categories/1
Accept: application/json

### Create a new category
POST {{dot_net_core_rest_api_HostAddress}}/api/categories
Content-Type: application/json

{
  "code": "ELEC",
  "name": "Electronics"
}

### Update a category
PUT {{dot_net_core_rest_api_HostAddress}}/api/categories/1
Content-Type: application/json

{
  "code": "ELEC-V2",
  "name": "Electronics & Gadgets"
}

### Delete a category
DELETE {{dot_net_core_rest_api_HostAddress}}/api/categories/1

### Get weather forecast (default)
GET {{dot_net_core_rest_api_HostAddress}}/weatherforecast/
Accept: application/json

###
